VALIDATION_ERROR=400
UNAUTHENTICATED_ERROR=401
FORBIDDEN_ERROR=403
NOTFOUND_ERROR=404
SERVER_ERROR=500

module.exports = {
    VALIDATION_ERROR,
    UNAUTHENTICATED_ERROR,
    FORBIDDEN_ERROR,
    NOTFOUND_ERROR,
    SERVER_ERROR
}